version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/Models/random_forest_model_passengers_count:/app/Models/random_forest_model_passengers_count
      - ./backend/Models/random_forest_model_total_amount:/app/Models/random_forest_model_total_amount
    container_name: backend
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    depends_on:
      - backend
    container_name: frontend